version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: microservice_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: microservice
    volumes:
      - mongodb_data:/data/db
    networks:
      - microservice_network

  # Go CRUD Service
  go-crud:
    build:
      context: ./CRUD-GO
      dockerfile: Dockerfile.prod
    container_name: go_crud_service
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
      - .env.local
    depends_on:
      - mongodb
    volumes:
      - ./CRUD-GO:/app
    networks:
      - microservice_network

  #Nginx Reverse Proxy
  nginx:
    build: ./nginx
    image: nginx
    container_name: "nginx_cont"
    ports:
      - "80:80"
    restart: always
    depends_on:
      - go-crud
      - node-auth
  # Node.js Auth Service
  node-auth:
    build:
      context: ./AUTH-NODE
      dockerfile: Dockerfile.prod
    container_name: node_auth_service
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
      - .env.local
    depends_on:
      - mongodb
    volumes:
      - ./AUTH-NODE:/app
      - /app/node_modules
    networks:
      - microservice_network

volumes:
  mongodb_data:

networks:
  microservice_network:
    driver: bridge